# Date,Open,High,Low,Close,Adj Close,Volume

COLUMNS:
  Date: object
  Open: float64
  High: float64
  Low: float64
  Close: float64
  Adj Close: float64
  Volume: float64


TARGET_COLUMN: 
  name: Close